[package]
name = "lang2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.37"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["rc", "derive"] }
serde_json = "1.0.89"
